
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								SPELL TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________



DEFINE_ACTION_FUNCTION tweak_good_berry BEGIN
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~SPELL.IDS~ ~[ %TAB%]WIZARD_DECASTAVE[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_GOOD_BERRIES~ RET spell_res END
  COPY_EXISTING ~%spell_res%.spl~ ~override~
	READ_LONG 0x34 res_level

  OUTER_SPRINT nuberry_desc @12072
  OUTER_INNER_PATCH_SAVE level_berry_desc ~%nuberry_desc%~ BEGIN
	REPLACE_TEXTUALLY ~Level: 2~ ~Level: %res_level%~
  END

  COPY ~d5_goodberry/data/spell_tweaks/d5goodb.spl~ ~override/%spell_res%.spl~
	SAY NAME1 @12071
	SAY UNIDENTIFIED_DESC ~%level_berry_desc%~
	LPF ALTER_EFFECT INT_VAR power = 0 END
	WRITE_LONG 0x34 res_level
END

COPY ~d5_goodberry/data/spell_tweaks/d5goodb.spl~ ~override/sppr207.spl~
  SAY NAME1 @12071
  SAY UNIDENTIFIED_DESC @12072
  LPF ALTER_EFFECT INT_VAR power = 0 END
  WRITE_LONG 0x34 2

ACTION_IF (GAME_IS ~iwdee~) BEGIN
  COPY_EXISTING ~sppr207.spl~ ~override/sppr215.spl~
END

END


//__________________________________________________________________________________
