
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								MONSTER TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


//DEFINE_ACTION_FUNCTION personal_monster_changes BEGIN


// vampires/level drain_____________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_vampires BEGIN
// level drain allows save
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 216 match_savingthrow = 0 savingthrow = 4 END
  END
BUT_ONLY

END
//__________________________________________________________________________________


// monster stats_________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_monster_stats BEGIN
COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
	READ_LONG 0x28 animation
	PATCH_IF (animation = 57949) BEGIN 			// 	yeti
	  WRITE_BYTE 0x238 18
	  WRITE_BYTE 0x239 99
	END
  END
  BUT_ONLY
END
//__________________________________________________________________________________


// monster (dragon) stats_________________________________________________________________________
//
DEFINE_ACTION_FUNCTION buff_dragon_hp INT_VAR hp_multiplier = 3 BEGIN
	COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
	  READ_BYTE 0x272 race
	  PATCH_IF race = 146 BEGIN
		READ_SHORT 0x24 max_hp
		READ_SHORT 0x26 cur_hp
		SET mid_max_hp = (max_hp * %hp_multiplier%)
		SET new_max_hp = (mid_max_hp / 2)
		SET mid_cur_hp = (cur_hp * %hp_multiplier%)
		SET new_cur_hp = (mid_cur_hp / 2)
		WRITE_SHORT 0x24 new_max_hp
		WRITE_SHORT 0x26 new_cur_hp
	  END
	BUT_ONLY
END
//__________________________________________________________________________________


// golems___________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_golems BEGIN
// reduce MR and DR
// apply free action
// apply immunity to charm, confusion, fear, berserk, sleep, 
// flesh = vulnerable to slashing & fire
// clay = vulnerable to crushing & cold
// stone = vulnerable to piercing & acid
// iron = vulnerable to electricity
// add some stuff to compensate?  (aura to reduce caster level?)

END
//__________________________________________________________________________________


// rakshasa_________________________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_rakshasas BEGIN
// make magic immunity dispellable?
// or reducible
// by breach and/or RRR/Spellstrike

END
//__________________________________________________________________________________

