
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								ITEM TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


//DEFINE_ACTION_FUNCTION personal_item_tweaks BEGIN


// ring of danger sense_____________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_ring_danger_sense BEGIN
// AC, backstab immunity, spell evasion
COPY_EXISTING ~ring36.itm~ ~override~
  SAY IDENTIFIED_DESC @30102
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 292 target = 1 parameter2 = 1 timing = 2 END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 END
// 
END
//__________________________________________________________________________________


// gloves of missile snaring________________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_gloves_missile_snaring BEGIN
// block 1 missile per round

LAF d5_resolve_state STR_VAR new_state_id = ~D5_SNAREARROW~ RET new_state_ind END
OUTER_SET missile_snaring_state = %new_state_ind%
OUTER_SET nada = RESOLVE_STR_REF (~ ~)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~7eyes.2da~ BEGIN
	COPY ~d5_random_tweaks/data/item_tweaks/7eyes.2da~ ~override~
END
APPEND ~7eyes.2da~ ~SNARE_ARROW  %missile_snaring_state%         %nada%         12*0x800000 *           *           *            *            *          *          *          * ~ UNLESS ~SNARE_ARROW~
COPY_EXISTING ~7eyes.2da~ ~override~
  COUNT_2DA_ROWS 1 rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 0 1 tag
	PATCH_IF (~%tag%~ STRING_EQUAL_CASE ~SNARE_ARROW~) BEGIN
	  SET 7eyes_row = row
	END
  END
BUT_ONLY

CREATE EFF ~d5misgl~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x18 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 0
  WRITE_LONG 0x28 600
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5misgl1~ #8
  WRITE_LONG 0x28 102

COPY ~d5_random_tweaks/misc/d5_base.spl~ ~override/d5misgl1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5misgl1~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 335 target = 1 power = 0 parameter1 = %missile_snaring_state% parameter2 = %7eyes_row% timing = 0 duration = 7 END

COPY_EXISTING ~brac18.itm~ ~override~
  SAY IDENTIFIED_DESC @30202
  LPF DELETE_EFFECT INT_VAR match_opcode = 0 match_parameter2 = 2 END
  LPF DELETE_EFFECT INT_VAR match_opcode = 83 END
  LPF DELETE_EFFECT INT_VAR match_opcode = 305 END
  LPF DELETE_EFFECT INT_VAR match_opcode = 206 STR_VAR match_resource = ~spra303~ END
  LPF DELETE_EFFECT INT_VAR match_opcode = 206 STR_VAR match_resource = ~spwi311~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 328 target = 1 parameter2 = %missile_snaring_state% timing = 2 END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 2 STR_VAR resource = ~d5misgl~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 0 target = 1 parameter1 = 3 parameter2 = 2 timing = 2 END
IF_EXISTS BUT_ONLY

END
//__________________________________________________________________________________


// weapons that explode on hit_______________________________________________________
//
DEFINE_ACTION_FUNCTION tweak_detonating_weapons BEGIN

ADD_PROJECTILE ~d5_random_tweaks/misc/b_pfire.pro~ 
COPY ~d5_random_tweaks/misc/PFIREA.bam~ ~override~
COPY ~d5_random_tweaks/misc/PFIREX.bam~ ~override~
COPY ~d5_random_tweaks/misc/#PRFIRE.vvc~ ~override~
COPY ~d5_random_tweaks/misc/#EFF_P45.WAV~ ~override~
COPY ~d5_random_tweaks/misc/#ARE_P03.WAV~ ~override~

COPY ~d5_random_tweaks/misc/d5_base.spl~ ~override/d5detwp.spl~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = %b_pfire% END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 2 parameter2 = 43 timing = 0 duration = 0 STR_VAR resource = ~%SOURCE_RES%~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 12 target = 2 power = 4 parameter1 = 0 parameter2 = 8 timing = 1 dicenumber = 5 dicesize = 6 savingthrow = (1 << 24) END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 power = 4 parameter1 = (0 - 1) timing = 0 duration = 6 STR_VAR resource = ~d5detwp~ END

COPY_EXISTING ~blun26.itm~ ~override~
			  ~blun26.itm~ ~override~
			  ~bdstaf03.itm~ ~override~
	LPF ALTER_EFFECT INT_VAR header_type = 1 match_opcode = 146 STR_VAR resource = ~d5detwp~ END
IF_EXISTS BUT_ONLY

END
//__________________________________________________________________________________

